# Generated by Django 5.0.3 on 2024-04-02 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Role', models.CharField(max_length=30)),
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('user_password', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('RoomID', models.AutoField(primary_key=True, serialize=False)),
                ('RoomName', models.CharField(max_length=100)),
                ('Facilities', models.CharField(max_length=255)),
                ('Capacity', models.IntegerField()),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('BookingID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('TimeSlot', models.CharField(max_length=100)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom_pro.room')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('ApprovalID', models.AutoField(primary_key=True, serialize=False)),
                ('ApprovalStatus', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('ApprovedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom_pro.booking')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('TimeSlot', models.CharField(max_length=100)),
                ('AvailabilityStatus', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], max_length=20)),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom_pro.room')),
            ],
            options={
                'unique_together': {('Room', 'Date', 'TimeSlot')},
            },
        ),
    ]
