# Generated by Django 5.0.3 on 2024-04-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='SStatus',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
