# Generated by Django 5.0.3 on 2024-04-03 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_pro', '0002_booking_sstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='SStatus',
            new_name='Status',
        ),
    ]
