# Generated by Django 5.0.3 on 2024-04-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_pro', '0003_rename_sstatus_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_password',
        ),
    ]
