# Generated by Django 5.0.3 on 2024-04-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_pro', '0005_approval_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='Comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
