# Generated by Django 5.0.3 on 2024-04-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_pro', '0006_alter_approval_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Comments',
            field=models.CharField(default='no comments', max_length=100),
        ),
    ]
